GNU_TOOLCHAIN_FOR_ARC_BASE := /usr/local/gsi-apu/13.7.1/ubuntu_20_04/arc_gnu_2021.09-release_elf32_le_linux_no_sdata/arc-snps-elf/
export PATH:=${GNU_TOOLCHAIN_FOR_ARC_BASE}/bin:${PATH}

lab_name := rag
TOP_DIR  := $(shell pwd)
include $(TOP_DIR)/Common/common.mk